sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ybc

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tG5rgXUWRn2YTqLHUBQ
    access-key-secret: bSBjFqhEYTc5qvi8pszVgejyMQzgUL
    bucket-name: springboot-tlias123

  redis:
    host: localhost
    port: 6379
    database: 10
    password: 138588

  wechat:
    appid: wx4458b0b90daf711f
    secret: b1615d3fecd53505ec8fa76f22558c07
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://6d9868b6.r2.cpolar.top
    refundNotifyUrl: https://6d9868b6.r2.cpolar.top
