sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ybc

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tG5rgXUWRn2YTqLHUBQ
    access-key-secret: bSBjFqhEYTc5qvi8pszVgejyMQzgUL
    bucket-name: springboot-tlias123

  redis:
    host: localhost
    port: 6379
    database: 10
    password: 138588

  wechat:
    appid: wx4458b0b90daf711f
    secret: b1615d3fecd53505ec8fa76f22558c07
